### ISSUE TITLE
New login flow for Duquesne Light (DQE) breaks Opower integration

### ISSUE THREAD

**Issue by cisasteelersfan** [tronikos/opower#83]
Hi there, I noticed (within the last few days) that Home Assistant wasn't updating my Duquesne Light Opower stats. 

Full logs (from Home Assistant):
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/opower/opower.py", line 197, in async_login
    self.access_token = await self.utility.async_login(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/opower/utilities/duquesnelight.py", line 91, in async_login
    async with session.post(
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 1197, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 696, in _request
    resp.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1070, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('https://www.duquesnelight.com/login/login')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/update_coordinator.py", line 312, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/components/opower/coordinator.py", line 81, in _async_update_data
    await self.api.async_login()
  File "/usr/local/lib/python3.12/site-packages/opower/opower.py", line 205, in async_login
    raise CannotConnect(err)
opower.exceptions.CannotConnect: 404, message='Not Found', url=URL('https://www.duquesnelight.com/login/login')
```

Indeed, I'm not able to access https://www.duquesnelight.com/login/login in the browser either.

From the Duquesne Light homepage, it appears login has moved to https://auth.duquesnelight.com/oauth/authorize/?client_id=33292caf-08ce-4631-a7a1-7bc3e30d318c&response_type=code&redirect_uri=https%3a%2f%2fduquesnelight.com%2fdlc%2flogin%3fredirectUrl%3d%252faccount-billing%252faccount-summary (concise, right?). 

I saw that @swartzd was the original creator of this utility integration in #68. I poked around in the code, replacing all of the headers and payload with the new values that I copied from my Chrome network tools console, however I'm getting `opower.exceptions.CannotConnect: 408, message='Request Timeout', url=URL('https://auth.duquesnelight.com/oauth/authorize?client_id=33292caf-08ce-4631-a7a1-7bc3e30d318c&response_type=code&redirect_uri=https://www.duquesnelight.com/dlc/login?redirectUrl%3D%252faccount-billing%252faccount-summary')`.

Would appreciate it if someone else could take a look. Thanks!!

**Comment by swartzd** [comment]
I will take a look at this within the next few days! I noticed this as well but had not yet had time to investigate.

**Comment by swartzd** [comment]
Just want to update: I have figured out the new login endpoint but I have yet to make the whole flow work again. Thanks for your patience

**Comment by swartzd** [comment]
I've got website login/authentication working but all further page access is getting blocked by incapsula/imperva. I have spent considerable time trying to make it work without success (not giving up but also do not have any light at the end of the tunnel)

**Comment by pioto** [comment]
Thanks for giving this a go. I had tried to write this integration myself a few months ago but their Incapsula/Imperva WAF was a problem then as well (it looks like you made some headway with additional headers to be more browser-y).

Doubtful, but in case anything I had tried helps you: https://github.com/tronikos/opower/compare/main...pioto:opower:duquesnelight

**Comment by tbutz12** [comment]
Hello @swartzd  - just wanted to thank you for your efforts so far as I have been using this integration on my HA. Is there any update on this by chance?

**Comment by swartzd** [comment]
I haven't made any progress. Getting burned by incapsula/imperva no matter if I try to look normal or not.  I will push my local branch up to see if anyone else has some brilliant ideas

**Comment by treed593** [comment]
If anyone has made any progress and can share their code I would be happy to take a look.

**Comment by tbutz12** [comment]
Does anyone else have any inputs here? Not having this supported is a real bummer.

**Comment by cisasteelersfan** [comment]
Here's what I tried: 

* downloaded an old version of Duquesne's Android app (3.0) that doesn't use the new login flow
* set up `mitmproxy` to capture traffic
* reproduced the requests in Python

And it still doesn't work - I also always get burned by Imperva / Incapsula. I'm able to get the JWT but not GET `/energy-money-savings/my-electric-use`.

The old Android app logs in by POSTing to some Azure endpoint which returns a JWT ("accessToken"). Then in subsequent GET requests to duquesnelight.com it sets the Cookie "authToken" equal to the JWT. 

If it's helpful to anyone, here's what `mitmproxy` shows for logging in and getting to the Opower token page:

## POST to Azure:
```
POST /mobile/v1/authenticate HTTP/1.1
Accept: application/json
Ocp-Apim-Subscription-Key: 4f2c4ef93d3448599a17f460680123d0
Content-Type: application/json; charset=utf-8
Content-Length: *redacted*
Host: shared-prod-prd-api-mgmt.azure-api.net

{"Username":"*redacted*","Password":"*redacted*","RedFlagPassword":null}

HTTP/1.1 200 OK
Content-Length: *redacted*
Content-Type: application/json; charset=utf-8
Request-Context: appId=cid-v1:09bbbf43-0e79-4688-b501-a5cb9f8cdc11
Date: Sat, 01 Feb 2025 22:11:35 GMT

{"accessToken":"*redacted*","azureMobileClientSecret":"*redacted*","westernUnionUsername":"*redacted*","westernUnionPassword":"*redacted*"}
```
(No idea what that westernUnion stuff is about)

## GET `/energy-money-savings/my-electric-use`
```
GET /energy-money-savings/my-electric-use HTTP/1.1
Host: www.duquesnelight.com
Connection: keep-alive
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Linux; Android 11; Android SDK built for arm64 Build/RSR1.210722.013.A4; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/83.0.4103.120 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
X-Requested-With: com.mobile.DuquenseLight
Sec-Fetch-Site: none
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Cookie: AuthToken=*redacted - from above*
content-length: 0



HTTP/1.1 200 OK
Content-Length: 104187
Content-Type: text/html; charset=utf-8
Date: Sat, 01 Feb 2025 22:12:21 GMT
Server: Microsoft-IIS/10.0
Cache-Control: no-cache
Expires: -1
Pragma: no-cache
Set-Cookie: ASP.NET_SessionId=*redacted*; path=/; HttpOnly; SameSite=Lax
Set-Cookie: __RequestVerificationToken=*redacted*; path=/; HttpOnly
Vary: Accept-Encoding
X-Frame-Options: SAMEORIGIN
X-Frame-Options: SAMEORIGIN
X-AspNet-Version: 4.0.30319
Request-Context: appId=cid-v1:4b92409f-3011-43eb-bc38-afa166ddc6aa
X-Powered-By: ASP.NET
Content-Security-Policy: frame-ancestors 'self'
Set-Cookie: visid_incap_2721902=*redacted*; expires=Sun, 01 Feb 2026 10:09:25 GMT; HttpOnly; path=/; Domain=.duquesnelight.com
Set-Cookie: nlbi_2721902=*redacted*; HttpOnly; path=/; Domain=.duquesnelight.com
Set-Cookie: incap_ses_410_2721902=*redacted*==; path=/; Domain=.duquesnelight.com
X-CDN: Imperva
X-Iinfo: 17-86966038-86966049 NNNN CT(20 46 0) RT(1738447940497 45) q(0 0 1 0) r(1 4) U24



<!DOCTYPE HTML>
[...]
"OPowerToken": 
[...]
```

Yet the ~same request in Python (captured by `mitmproxy` as well) is hit with Incapsula:
```
GET /energy-money-savings/my-electric-use HTTP/1.1
Host: www.duquesnelight.com
Accept-Encoding: deflate, gzip
Connection: keep-alive
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Linux; Android 11; Android SDK built for arm64 Build/RSR1.210722.013.A4; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/83.0.4103.120 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
X-Requested-With: com.mobile.DuquenseLight
Sec-Fetch-Site: none
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Accept-Language: en-US,en;q=0.9
Cookie: AuthToken=*redacted*
content-length: 0



HTTP/1.1 200 OK
Content-Type: text/html
Cache-Control: no-cache, no-store
Connection: close
Content-Length: 835
X-Iinfo: 18-103825570-0 0NNN RT(1738449675244 101) q(0 -1 -1 0) r(0 -1) B12(4,316,0) U24
Set-Cookie: visid_incap_2721902=*redacted; expires=Sun, 01 Feb 2026 10:09:10 GMT; HttpOnly; path=/; Domain=.duquesnelight.com
Set-Cookie: incap_ses_410_2721902=*redacted*; path=/; Domain=.duquesnelight.com

<html style="height:100%"><head><META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW"><meta name="format-detection" content="telephone=no"><meta name="viewport" content="initial-scale=1.0"><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"></head><body style="margin:0px;height:100%"><iframe id="main-iframe" src="/_Incapsula_Resource?*redacted*" frameborder=0 width="100%" height="100%" marginheight="0px" marginwidth="0px">Request unsuccessful. Incapsula incident ID: *redacted*</iframe></body></html>
```

**Comment by cisasteelersfan** [comment]
I've also tried using https://github.com/lexiforest/curl_cffi to try and make the TLS/JA3 fingerprint look more 'real' but that didn't seem to help. And tried ordering headers in the same way. 

I can't figure out how Imperva is detecting that the request isn't from a browser!

**Comment by swartzd** [comment]
Yeah it's the imperva/incapsula nonsense that has me stumped. I believe it's executing some JavaScript thing when using a legit web browser but we don't have a good way to do that. I'll try to document what methods I've tried in the next week or so - I haven't abandoned this but am completely defeated.

**Comment by esw148** [comment]
Checking in on this to see if there has been any progress. Assuming not, but wanted to check. I just tried to setup this integration and noticed the login issue and then found this github issue. I'm playing around with requests/responses to see if I can get anything to work too.

**Comment by dsevillamartin** [comment]
I decided to randomly give this a go, and think I got it working? Replacing the code with mine in HomeAssistant's deps allowed Opower to obtain data (and the CLI as well, this was just to fully check).

This is probably not the best way to do this, but it worked so could be used for further investigation. Not sure if it holds up to future requests. At the very least I hope this is useful? Didn't see a successful request to `my-electric-use` so thought I'd post.

The CLI obtained both "Current bill forecast" and "Getting historical data" successfully. And HomeAssistant integration also succeeded in fetching its data (once i replaced `opower` module code).

I added a simple GET to the login page to obtain whatever cookies the site may add, and then updated the login route.
Its URL was obtained from just looking at the "Login" code at https://www.duquesnelight.com/ -- I'd assume the client ID stays constant.

```py
# cookie jar clearing probably needs to have domain updated if double login remains an issue

headers = { ... }

# New GET request
await session.get(
    "https://auth.duquesnelight.com/oauth/authorize?client_id=33292caf-08ce-4631-a7a1-7bc3e30d318c&response_type=code&redirect_uri=https:%2F%2Fwww.duquesnelight.com%2Fdlc%2Flogin%3FredirectUrl%3D%252faccount-billing%252faccount-summary"
)

# Updated POST login
async with session.post(
    "https://auth.duquesnelight.com/oauth/authorize/login",
    data={
        "grant_type": "password",
        "remember_username": True,
        "username": username,
        "password": password,
    },
    headers=headers,
) as resp:
    # Looks like the new API properly uses HTTP status codes (400 for invalid auth).
    # And returns an error as string when failed, otherwise 200 with no response I believe -- this can be updated
    if "invalid" in await resp.text():
        raise InvalidAuth("Invalid auth")

# Keep old GET .../my-electric-use code
```

**Comment by tronikos** [comment]
Could you submit a PR?

**Comment by dsevillamartin** [comment]
@tronikos Sure - it actually worked without that GET I added (simply by updating POST req, I updated my comment), so I think Duquesne changed something with the WAF since I have not managed to hit it at all.

**Comment by pioto** [comment]
I've locally tested the changes on @dsevillamartin's PR (#137), and it seems like it's working for me as well!

**Comment by tbutz12** [comment]
@weinshel is there a way i can get it without it being merged yet?
